# Generated by Django 2.1 on 2019-11-12 14:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('potter_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('gallery_img', models.ImageField(default='', upload_to='uploads/gallery', verbose_name='Image')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='potter_app.Category')),
            ],
        ),
    ]
